routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/master', function (){
    return view('templates/master');
});

Route::get('/items', function(){
    return view('items.index');
});

Route::get('/', function(){
    return view('tugasharian.table');
});

Route::get('/data-tables', function(){
    return view('tugasharian.data-table');
});

// Route::get('/cast', 'CastController@index');
// Route::get('/cast/create', 'CastController@create');
// Route::post('/cast', 'CastController@store');
// Route::get('/cast/{cast_id}', 'CastController@show');
// Route::get('/cast/{cast_id}/edit', 'CastController@edit');
// Route::put('/cast/{cast_id}','CastController@update');
// Route::delete('/cast/{cast_id}','CastController@destroy');

Route::resource('cast', 'CastController');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Cast.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cast extends Model
{
    //
    protected $table = 'cast';
    protected $guarded = [];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','username',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/CastController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Cast;
use Auth;

class CastController extends Controller
{
	public function __construct(){
		$this->middleware('auth')->only(['create','store','edit','update','delete']);
	}
	public function index(){
		// $cast = DB::table('cast')->get();
		$cast = Cast::all();
		return view('cast.index', compact('cast'));
	}
	public function create(){
		return view('cast.create');
	}
	public function store(Request $request){
		$request->validate([
			'name' => 'required',
			'age' => 'required',
			'bio' => 'required'
		]);
		// $query = DB::table('cast')->insert([
		// 	'name'=>$request["name"],
		// 	'age'=>$request["age"],
		// 	'bio'=>$request["bio"]
		// ]);
		// $cast = new Cast;
		// $cast->name = $request['name'];
		// $cast->age = $request['age'];
		// $cast->bio = $request['bio'];
		// $cast->save();
		$cast = Cast::create([
			"name" => $request["name"],
			"age" => $request["age"],
			"bio" => $request["bio"]
		]);
		return redirect('/cast')->with('success', 'Cast Berhasil disimpan');
	}
	public function show($id){
		// $cast = DB::table('cast')->where('id',$id)->first();
		$cast = Cast::find($id);
		return view('cast.show', compact('cast'));
	}
	public function destroy($id){
		// $query = DB::table('cast')->where('id',$id)->delete();
		$cast = Cast::destroy($id);
		return redirect('/cast');
	}
	public function edit($id){
		// $cast = DB::table('cast')->where('id',$id)->first();
		$cast = Cast::find($id);
		return view('cast.edit', compact('cast'));
	}
	public function update($id, Request $request){
		// $request->validate([
		// 	'name' => 'required',
		// 	'age' => 'required',
		// 	'bio' => 'required',
		// ]);
		// $query = DB::table('cast')->where('id',$id)->update([
		// 	'name'=>$request['name'],
		// 	'age'=>$request['age'],
		// 	'bio'=>$request['bio'],
		// ]);
		$cast = Cast::where('id',$id)->update([
			"name" => $request["name"],
			"age" => $request["age"],
			"bio" => $request["bio"]
		]);
		return redirect('/cast');
	}
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/cast/create.blade.php
@extends('templates.master')
@section('content')    
	<div>
		<h2>Tambah Data</h2>
			<form action="/cast" method="POST">
				@csrf
				<div class="form-group">
					<label for="name">Name</label>
					<input type="text" class="form-control" name="name" id="name" placeholder="Masukkan Name">
					@error('name')
						<div class="alert alert-danger">
							{{ $message }}
						</div>
					@enderror
				</div>
				<div class="form-group">
					<label for="age">Age</label>
					<input type="text" class="form-control" name="age" id="age" placeholder="Masukkan Age">
					@error('age')
						<div class="alert alert-danger">
							{{ $message }}
						</div>
					@enderror
				</div>
				<div class="form-group">
					<label for="bio">Bio</label>
					<input type="text" class="form-control" name="bio" id="bio" placeholder="Masukkan Bio">
					@error('bio')
						<div class="alert alert-danger">
							{{ $message }}
						</div>
					@enderror
				</div>
				<button type="submit" class="btn btn-primary">Tambah</button>
			</form>
	</div>
@endsection

resources/views/cast/edit.blade.php
@extends('templates.master')
@section('content')    
  <div>
    <h2>Edit Cast {{$cast->id}}</h2>
    <form action="/cast/{{$cast->id}}" method="POST">
        @csrf
        @method('PUT')
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" name="name" value="{{$cast->name}}" id="name" placeholder="Masukkan Name">
            @error('name')
                <div class="alert alert-danger">
                    {{ $message }}
                </div>
            @enderror
        </div>
        <div class="form-group">
            <label for="age">age</label>
            <input type="text" class="form-control" name="age"  value="{{$cast->age}}"  id="age" placeholder="Masukkan Age">
            @error('age')
                <div class="alert alert-danger">
                    {{ $message }}
                </div>
            @enderror
        </div>
        <div class="form-group">
          <label for="bio">bio</label>
          <input type="text" class="form-control" name="bio"  value="{{$cast->bio}}"  id="bio" placeholder="Masukkan Bio">
          @error('bio')
              <div class="alert alert-danger">
                  {{ $message }}
              </div>
          @enderror
      </div>
        <button type="submit" class="btn btn-primary">Edit</button>
    </form>
  </div>
@endsection

resources/views/cast/index.blade.php
@extends('templates.master')
@section('content')
<a href="{{route('cast.create')}}" class="btn btn-primary">Tambah</a>
<table class="table">
	<thead class="thead-light">
		<tr>
			<th scope="col">id</th>
			<th scope="col">name</th>
			<th scope="col">age</th>
			<th scope="col">bio</th>
			<th scope="col">created_at</th>
			<th scope="col">updated_at</th>
			<th scope="col">Actions</th>
		</tr>
	</thead>
	<tbody>
		@forelse ($cast as $key=>$value)
			<tr>
				<td>{{$value->id}}</th>
				<td>{{$value->name}}</td>
				<td>{{$value->age}}</td>
				<td>{{$value->bio}}</td>
				<td>{{$value->created_at}}</td>
				<td>{{$value->updated_at}}</td>
				<td>
					<a href="{{route('cast.show',['cast'=> $value->id])}}" class="btn btn-info">Show</a>
					<a href="{{ route('cast.edit',['cast'=> $value->id])}}" class="btn btn-primary">Edit</a>
					<form action="{{ route('cast.destroy',['cast' => $value->id]) }}" method="POST">
						@csrf
						@method('DELETE')
						<input type="submit" class="btn btn-danger my-1" value="Delete">
					</form>
				</td>
			</tr>
		@empty
			<tr colspan="3">
				<td>No data</td>
			</tr>  
		@endforelse              
	</tbody>
</table>
@endsection

resources/views/cast/show.blade.php
@extends('templates.master')
@section('content')
	<h2>Show Cast {{$cast->id}}</h2>
	<h4>{{$cast->name}}</h4>
	<p>{{$cast->age}}</p>
	<p>{{$cast->bio}}</p>
	<p>{{$cast->created_at}}</p>
	<p>{{$cast->updated_at}}</p>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/items/index.blade.php
@extends('templates.master')

@section('content')
<h1>Hello Wolrd!</h1>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/templates/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>AdminLTE 3 | Blank Page</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{asset('AdminLTE-3.1.0/plugins/fontawesome-free/css/all.min.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('AdminLTE-3.1.0/dist/css/adminlte.min.css')}}">
</head>
<body class="hold-transition sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">
  <!-- Navbar -->
  @include('templates.partials.navbar')
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  @include('templates.partials.sidebar')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    @yield('content')
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 3.1.0
    </div>
    <strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{{asset('AdminLTE-3.1.0/plugins/jquery/jquery.min.js')}}"></script>
<!-- Bootstrap 4 -->
<script src="{{asset('AdminLTE-3.1.0/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('AdminLTE-3.1.0/dist/js/adminlte.min.js')}}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{asset('AdminLTE-3.1.0/dist/js/demo.js')}}"></script>

@stack('scripts')
</body>
</html>

resources/views/templates/partials/navbar.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{{asset('AdminLTE-3.1.0/index3.html')}}" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{asset('AdminLTE-3.1.0/dist/img/user1-128x128.jpg')}}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{asset('AdminLTE-3.1.0/dist/img/user8-128x128.jpg')}}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="{{asset('AdminLTE-3.1.0/dist/img/user3-128x128.jpg')}}" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>

resources/views/tugasharian/table.blade.php
@extends('templates.master')
@section('content')
	<table class="table table-bordered">
		<thead>                  
			<tr>
				<th style="width: 10px">#</th>
				<th>Task</th>
				<th>Progress</th>
				<th style="width: 40px">Label</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>1.</td>
				<td>Update software</td>
				<td>
					<div class="progress progress-xs">
						<div class="progress-bar progress-bar-danger" style="width: 55%"></div>
					</div>
				</td>
				<td><span class="badge bg-danger">55%</span></td>
			</tr>
			<tr>
				<td>2.</td>
				<td>Clean database</td>
				<td>
					<div class="progress progress-xs">
						<div class="progress-bar bg-warning" style="width: 70%"></div>
					</div>
				</td>
				<td><span class="badge bg-warning">70%</span></td>
			</tr>
			<tr>
				<td>3.</td>
				<td>Cron job running</td>
				<td>
					<div class="progress progress-xs progress-striped active">
						<div class="progress-bar bg-primary" style="width: 30%"></div>
					</div>
				</td>
				<td><span class="badge bg-primary">30%</span></td>
			</tr>
			<tr>
				<td>4.</td>
				<td>Fix and squish bugs</td>
				<td>
					<div class="progress progress-xs progress-striped active">
						<div class="progress-bar bg-success" style="width: 90%"></div>
					</div>
				</td>
				<td><span class="badge bg-success">90%</span></td>
			</tr>
		</tbody>
	</table>
@endsection